#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include "inc/log.h"
#include "inc/asprintf.h"

static void write_makefile();
static void create_directories();
static void write_license();
static void write_readme();
static int write_main();

static char *proj_name;
static int do_makefile = 1;
static int do_readme = 1;
static int do_license = 1;
static int do_main = 1;
static char *cmd; /* final form of command to be executed */

int main(int argc, char **argv){

  if(argc < 2){
    bm_log_err("Need to specify project name\n");
    return -1;
  }
  
  proj_name = argv[1];
  bm_log_info("Project name: [%s]\n", proj_name);  
  
  int opt;
  while((opt = getopt(argc, argv, "rlmf")) != -1){
    switch(opt){

    case 'r':
      //don't create readme file
      do_readme = 0;
      break;

    case 'l':
      //don't create license file
      do_license = 0;
      break;

    case 'm':
      //don't create makefile
      do_makefile = 0;
      break;

    default:
      bm_log_err("Dunno what you mean\n");
      return -1;
    }
  }

  /* start */
  struct stat st = {0};
  if(stat(proj_name, &st) == -1){
    bm_log_info("Creating directory [%s].\n", proj_name);
    if(mkdir(proj_name, 0755) != -1){
      create_directories();

      if(do_readme){
	write_readme();
      }

      if(do_license){
	write_license();
      }

      if(do_makefile){
	write_makefile();
      }
      if(do_main){
	write_main();
      }
      bm_log_info("Workspace setup finished.\n");
    }
  }else{
    bm_log_info("Directory [%s] already exists.\n", proj_name);
  }
  return 0;
}

static int write_main(){
  char *main_path;
  asprintf(&main_path, "%s/src/main.c", proj_name);
  asprintf(&cmd, 
	   "echo '#include <stdlib.h>\n#include <stdio.h>\n\n\n\n\
            \nint main(int argc, char **argv){\n\n\nprintf(\"Ughachacka ugha ugha!!!\\n\");return 0;\n}' > %s", main_path, proj_name);
  system(cmd);
  bm_log_info("Created  main.c\n");
  free(main_path);
  free(cmd);
  
  /* TODO: could test here if build OK */
  return 0;
}

static void write_license(){
  char *lic_path;
  asprintf(&lic_path, "%s/%s", proj_name, "LICENSE");
  asprintf(&cmd, "touch %s >/dev/null 2>&1", lic_path);
  system(cmd);
  bm_log_info("License path: [%s]\n", lic_path);
  free(lic_path);
  free(cmd);
}

static void write_readme(){
  char *readme_path;
  asprintf(&readme_path, "%s/%s", proj_name, "README.md");
  asprintf(&cmd, "touch %s >/dev/null 2>&1", readme_path);
  system(cmd);
  bm_log_info("Readme path: [%s]\n", readme_path);
  free(readme_path);
  free(cmd);
}

static void create_directories(){
  char *src_dir, *inc_dir, *build_dir, *bin_dir;
  asprintf(&src_dir, "%s/%s", proj_name, "src");
  asprintf(&inc_dir, "%s/%s", src_dir, "inc");
  asprintf(&build_dir, "%s/%s", proj_name, "build");
  asprintf(&bin_dir, "%s/%s", proj_name, "bin");
  mkdir(src_dir, 0755);
  mkdir(inc_dir, 0755);
  mkdir(bin_dir, 0755);
  mkdir(build_dir, 0755);
  free(src_dir);
  free(inc_dir);
  free(bin_dir);
  free(build_dir);
}

static void write_makefile(){
  
  char *makefile = strdup("#Autogenerated Makefile\n\
\nRM=/bin/rm \
\nMKDIR=/bin/mkdir -p \
\nGCC=gcc \
\nNAME=%s \
\nLFLAGS =					       \
\nCFLAGS = -Wall -g -o3 -std=gnu99 \
\nSRC=src\
\nBUILD=build\
\nBIN=bin\
\nS = $(wildcard $(SRC)/*.c) \
\nH = $(wildcard $(SRC)/inc/*.h) \
\nO = $(patsubst $(SRC)/%%.c, $(BUILD)/%%.o, $(S)) \
\n$(BIN)/$(NAME): $(O) \
\n\t@echo 'Linking...' \
\n\t@$(GCC) $(CFLAGS) -o $(BIN)/$(NAME) $(LFLAGS) $(O) \
\n\t@echo '..done' \
\n$(BUILD)/%%.o: $(SRC)/%%.c \
\n\t@$(MKDIR) $(BUILD) $(BIN) \
\n\t@$(GCC) $(CFLAGS) -c -o $@ $< \
\n\t@echo 'Compilation of $< finished' \
\n.PHONY: clean \
\nclean: \
\n\t@echo 'Deleting *.o files' \
\n\t@$(RM) $(O) \
\n\t@echo 'Deleting $(NAME) binary' \
\n\t@$(RM) $(BIN)/$(NAME)");
  
  char *mfile_path;
  asprintf(&mfile_path, "%s/%s", proj_name, "Makefile");
  FILE *mfile = fopen(mfile_path, "w+");
  if(mfile){
    /* write stuff to makefile */
    char *buf;
    asprintf(&buf, makefile, proj_name);
    bm_log_info("Wriiting stuff to makefile\n");
    fwrite(buf, 1, strlen(makefile), mfile);
    fclose(mfile);
    free(buf);
    free(mfile_path);
  }else{
    bm_log_err("Cannot create makefile\n");
    exit(EXIT_FAILURE);
  }
}
